### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by thebrandonhoward** [lazojs/lazo#177]
C:\Program Files\nodejs>npm install -g --production lazo
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/requirejs/text.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/amdjs/backbone.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/amdjs/underscore.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/jstrimpel/jquery-cookie.git)
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/jstrimpel/requirejs-plugins.git)
npm ERR! git clone git://github.com/amdjs/backbone.git Cloning into bare reposit
ory 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\g
it-github-com-amdjs-backbone-git-586d37a9'...
npm ERR! git clone git://github.com/amdjs/backbone.git fatal: Unable to look up
github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/amdjs/underscore.git Cloning into bare repos
itory 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes
\git-github-com-amdjs-underscore-git-e36fc557'...
npm ERR! git clone git://github.com/amdjs/underscore.git fatal: Unable to look u
p github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/requirejs/text.git Cloning into bare reposit
ory 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-remotes\g
it-github-com-requirejs-text-git-a4388600'...
npm ERR! git clone git://github.com/requirejs/text.git fatal: Unable to look up
github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/jstrimpel/requirejs-plugins.git Cloning into
 bare repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_
git-remotes\git-github-com-jstrimpel-requirejs-plugins-git-173ab38d'...
npm ERR! git clone git://github.com/jstrimpel/requirejs-plugins.git fatal: Unabl
e to look up github.com (port 9418) (No such host is known. )
npm ERR! git clone git://github.com/jstrimpel/jquery-cookie.git Cloning into bar
e repository 'C:\Documents and Settings\behowar\Application Data\npm-cache\_git-
remotes\git-github-com-jstrimpel-jquery-cookie-git-7f91dafe'...
npm ERR! git clone git://github.com/jstrimpel/jquery-cookie.git fatal: Unable to
 look up github.com (port 9418) (No such host is known. )
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Documents and S
ettings\behowar\Application Data\npm-cache\_git-remotes\git-github-com-amdjs-bac
kbone-git-586d37a9'...
npm ERR! fatal: Unable to look up github.com (port 9418) (No such host is known.
 )
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "--production" "lazo"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code 128
npm ERR! not ok code 0

C:\Program Files\nodejs>

**Comment by thebrandonhoward** [comment]
cleaned the cache....now getting the following:



C:\Program Files\nodejs>npm cache clean

C:\Program Files\nodejs>npm install -g lazo --production
npm ERR! Error: connect ECONNREFUSED
npm ERR!     at errnoException (net.js:904:11)
npm ERR!     at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR!  { [Error: connect ECONNREFUSED]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Windows_NT 5.1.2600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\no
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "lazo" "--production"
npm ERR! cwd C:\Program Files\nodejs
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! syscall connect
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! stack Error: connect ECONNREFUSED
npm ERR! stack     at errnoException (net.js:904:11)
npm ERR! stack     at Object.afterConnect [as oncomplete] (net.js:895:19)
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Program Files\nodejs\npm-debug.log
npm ERR! not ok code 0

**Comment by jstrimpel** [comment]
Postinstall moved to preinstall.
