### ISSUE TITLE
Problem saving models

### ISSUE THREAD

**Issue by adam-26** [lazojs/lazo#186]
A recent change now requires a second object to be passed to a model.save() call. The bug is caused by this line:
https://github.com/lazojs/lazo/blob/master/lib/public/model.js#L40

syncDataFromChildren is not assigned a default value, therefore save fails if it is not defined in the save functions options object. I assume it should be assigned a default value? This change has also caused the TodoMvc examples to fail when you try to mark an item as done.

**Comment by jstrimpel** [comment]
@adam-26 Thanks for catching this. We hope to have a patch release later today. Please use this version of TodoMVC, https://github.com/jstrimpel/todomvc/tree/lazo-example/examples/lazojs. We will be creating a new repo, lazojs/todomvc and housing it there. /cc @pknepper

**Comment by jstrimpel** [comment]
Fixed in v1.2.1 release.
