### ISSUE TITLE
Controller Navigate Bug

### ISSUE THREAD

**Issue by adam-26** [lazojs/lazo#197]
Hi,

Version 2 introduces a bug using "this.ctl.navigate('viewname')" when the controller exists in a component that is already rendered in a layout. When navigate is called, it is expected that the view name passed to the function is displayed, however this does not happen within a layout. No errors are thrown, but the view is not displayed.

You can verify this using the Lazo Todo MVC (V2) example. Add a button to the 'Main#index' view, and on click execute 'this.ctl.navigate('other');', create another view (other.hbs) file with some simple markup. Open the application using the '/layout' route and then click on the button. You will see that the 'other' view is not displayed.

Navigation works as expected when updating the browser URL using LAZO.app.navigate(this.ctx, 'other').

**Comment by jstrimpel** [comment]
+ lazo@2.0.2-alpha
