### ISSUE TITLE
Syncher enhancements

### ISSUE THREAD

**Issue by adam-26** [lazojs/lazo#208]
Hi,

I need to do the following from a syncher:
 - Access the request instance to determine information about the request (specifically, the users ip)
 - Write cookies to the response

I don't believe these are unusual requirements. Possible solutions could be:
#1: Add the req & reply args to the options parameter for all syncher functions (Example for non crud fns - https://github.com/lazojs/lazo/blob/master/lib/server/handlers/tunnel.js#L75)

#2: Pass a context instance to the options parameter for all syncher functions. However, i believe that the context instance would need to be a 'reduced context', from a syncher there is some data that you would not have access to. A simple solution could be to create a 'SyncherContext' class using the context.prototype (https://github.com/lazojs/lazo/blob/master/lib/common/context.js#L69), and extend this to create the full 'Context' class.

#3. Combine options 1 & 2, access to a context provides a consistent interface, while still allowing access to the request and reply instances when required. Or alternatively, add the request & reply to the 'SyncherContext'.

I'm happy to create a PR for this, just want some input/feedback before proceeding.

Thanks, Adam.

**Comment by pknepper** [comment]
Ok, just drafted this with Jason.  Here's our take:

The request and reply should only be available via private properties in the Context.  See https://github.com/lazojs/lazo/blob/master/lib/server/handlers/app/main.js#L5

So the tunnel handler should be updated to create a context with something similar.

That way the proxy in the Syncher will have access to it via it's context.  https://github.com/lazojs/lazo/blob/master/lib/server/proxy.js#L18

Ideally the hapi request info property should just be added to the Context as a public property. http://hapijs.com/api/6.7.1#request-properties  Like these other public properties https://github.com/lazojs/lazo/blob/master/lib/common/context.js#L61  make sure the client has the same property to ensure that it’s not undefined.

Looking forward to the PR.  Please ping us if you have any other questions.

**Comment by jstrimpel** [comment]
Fixed in v2.0.15-alpha.
