### ISSUE TITLE
Identifying tunnel requests

### ISSUE THREAD

**Issue by adam-26** [lazojs/lazo#215]
Hi,

You can use LAZO.app.isServer to identify if code is being executed on the server, but is it possible to identify if a request is a tunnel request on the server (as opposed to an first page load)? 

Thanks, Adam.

**Comment by jstrimpel** [comment]
@adam-26 We are a bit backlogged, but we got this issue and the others. We have blocked sometime next week to review. If anything is blocking please let me know.

**Comment by adam-26** [comment]
I have a solution for this, I'll submit a PR for comment.

**Comment by jstrimpel** [comment]
What is the use case for this?

**Comment by adam-26** [comment]
The use case is to support implementation of custom behavior for the client side proxy. The only way I could see to achieve this easily was by creating a custom Model and Collection class that extend the base lazoModel and lazoCollection classes, and override the sync() and call() functions, that then call their corresponding base functions. However, these functions are executed on both the client and the server (for first page load, and tunnel requests). The underlying lazoModel and lazoCollection functions load a proxy based on the {env} variable, I therefore don't think there is an easy way to override the client proxy (lib/client/proxy.js) behavior directly.

The 'isTunnelRequest' property provides the distinction of server-side first page loads vs tunnel requests. This is important because the client proxy must behave the same for server-side first page loads and client requests, but for tunnel requests data must be returned to the client for processing. Without this flag, it is only possible to identify if the request is executing on the client or the server. This flag ensures the same behavior on the client and the server first page load.

If there is a better way to achieve this, please let me know.

**Comment by jstrimpel** [comment]
Custom behavior being something like you want to source the data from
localStorage on the client?

**Comment by adam-26** [comment]
I'll try to clear this up a little :) Here are the two scenarios:

load or save a model/collection from the browser (client):
> controller -> model -> clientProxy (xhr) -> model (on server) -> serverProxy -> syncher

Process an initial page request on the server that loads a model/collection:
> controller -> model (on server) -> serverProxy -> syncher

Because the same model/collection `sync()/call()` functions are used on both client and server, when executing on the server I need to determine how to handle response from the serverProxy. If it's a tunnel request I send the response back to the client, if its a page rendering on the server then I need to use the same logic as the would execute on the client.

This logic would be better suited (and cleaner) if it could be moved to the proxy classes, but as they are loaded via requireJS, there is no way to tell the model/collection classes to use a different proxy (This could be easily implemented). But, even in this scenario the server proxy would still need a way to determine if it was serving a tunnel request.

When I refer to custom behavior, I pass in a custom options object that describes how to handle the response. So it's more about identifying how to handle a request/response than it is using an environment specific feature such as localStorage.
