### ISSUE TITLE
Bug: XSS Vulnerability

### ISSUE THREAD

**Issue by adam-26** [lazojs/lazo#228]
LAZO is vulnerable to XSS. For an example, follow this link (It doesn't do anything evil):
http://lazojs.org/?field=%22%3E%3Cscript%3Ealert%281%29%3B%3C%2Fscript%3E

I believe XSS could also be achieved via using crafted cookie content, as cookie data is also serialized into server responses. Is it possible to remove query string parameter data, and cookie data from the serialized server response?

**Comment by jstrimpel** [comment]
Thanks. The cookie data should be removed and we should be sanitizing the
query parameters.

**Comment by jstrimpel** [comment]
@adam-26 Can you please send email to jstrimpel@gmail.com. Thanks, Jason

**Comment by jstrimpel** [comment]
Fixed in v1.2.4 and v2.0.15-alpha. Query and path parameter values are now encoded in the first page load. The values are decoded during client initialization.
