### ISSUE TITLE
redirect whitelist support

### ISSUE THREAD

**Issue by vanessachem** [lazojs/lazo#236]
Does LAZO support  blocking off-site redirects via config or only allow redirect from a whitelist via a config?

Or that is something outside of framework scope?

**Comment by jstrimpel** [comment]
That would something that you put in a filter so that when `LAZO.app.navigate` is called you can redirect to another page.

**Comment by vanessachem** [comment]
LAZO.app.addRequestFilter can this be called multiple times?

**Comment by vanessachem** [comment]
here is the solution. you can do something like

LAZO.app.addRequestFilter('.*', function (path, params, ctx, options) {
          var hostname = ctx.location.hostname;
          var port = ctx.location.port;
          var hostMatchPattern;
          var redirectHost;
          var redirectUrl;
          hostMatchPattern = port ? hostname + ':' + port : hostname;
          redirectHost = getHostName(ctx.params.redirect);
            if (!(redirectHost === hostMatchPattern)) {
                //redirect to main host page
                return options.success(sslProtocol + '://' + hostname + (sslPort ? ':' + sslPort : ''));
            }
});

  function getHostName(url) {
        var regex = /^(?:https?:\/\/)?(?:www\.)?([^\/]+)/i;
        var redirectHostMatch = url.match(regex);
        var redirectHost;

        if (redirectHostMatch) {
            redirectHost = redirectHostMatch[1];
        }
        return redirectHost;
    }
