### ISSUE TITLE
where is the best place to config httpOnly and secure cookie?

### ISSUE THREAD

**Issue by vanessachem** [lazojs/lazo#238]
i was thinking about using ctx.setCookie.

then i found out 
http://hapijs.com/tutorials/cookies

you can set httpOnly and secure cookie when starts hapi server.

In LAZO application, where is the best place to config?

thanks

**Comment by jstrimpel** [comment]
`ctx.setCookie` abstracts cookie setting on the client and server. It would need to be modified to support this.

**Comment by vanessachem** [comment]
doing this will work.   
  ctx.setCookie('key1', encodeURIComponent(JSON.stringify(cpfa)), {
                expires: 60 * 60 * 1000,
                path: '/',
                isSecure :true,
                isHttpOnly: true
            });

now if you go to console, and do document.cookie, you cannot see the 'key1'.

thanks

**Comment by jstrimpel** [comment]
Does this work when setting the cookie on the client?

**Comment by vanessachem** [comment]
looks like it works. tested as below:

I inserted following lines into after render function. and looks like clientcookie is applied. 

  this.ctl.ctx.setCookie('clientcookie', 'niuniuniu', {
                expires: 60 * 60 * 1000,
                path: '/',
                // isSecure :true,
                // isHttpOnly: true
            });
