### ISSUE TITLE
Is this alive?

### ISSUE THREAD

**Issue by juanbrujo** [lazojs/lazo#320]
In the company I work we're working for Walmart on they'r new website 2016, so we're choosing a frontend library/framework and as LazoJS is a Walmart Labs project seems interesting have it as a candidate.

Is LazoJS project alive and being used in production? Thanks.

**Comment by jstrimpel** [comment]
While Lazo is still powering legacy applications it is no longer being supported. I would speak with Alexander Grigoryan to get more information on technology choices that are being leveraged and supported for the front-end.
